(1, 'United States', 'US'),
(2, 'Canada', 'CA'),
(3, 'United Kingdom', 'UK'),
(4, 'Ireland', 'IE'),
(5, 'Australia', 'AU'),
(6, 'Germany (Deutschland)', 'DE'),
(7, 'Netherlands (Nederland)', 'NL'),
(8, 'Mexico (México)', 'MX'),
(9, 'Spain (España)', 'ES'),
(10, 'Italy (Italia)', 'IT'),
(11, 'France', 'FR'),
(12, 'Belgium (Belgique)', 'BE'),
(13, 'Austria (Österreich)', 'AT'),
(14, 'Switzerland (Schweiz)', 'CH'),
(15, 'Denmark (Danmark)', 'DK'),
(16, 'Greece (Ελλάδα)', 'GR'),
(17, 'Iceland (Ísland)', 'IS'),
(18, 'Luxembourg', 'LU'),
(19, 'Malta', 'MT'),
(20, 'Norway (Norge)', 'NO'),
(21, 'Portugal', 'PT'),
(22, 'Sweden (Sverige)', 'SE'),
(23, 'Afghanistan', 'AF'),
(24, 'Albania (Shqipëria)', 'AL'),
(25, 'Armenia', 'AM'),
(26, 'Azerbaijan (Azərbaycan)', 'AZ'),
(27, 'Bosnia and Herzegovina (Bosna i Hercegovina)', 'BA'),
(28, 'Barbados', 'BB'),
(29, 'Bangladesh', 'BD'),
(30, 'Bulgaria (България)', 'BG'),
(31, 'Bermuda', 'BM'),
(32, 'Brunei', 'BN'),
(33, 'Bahamas', 'BS'),
(34, 'Belarus (Беларусь)', 'BY'),
(35, 'Chile', 'CL'),
(36, 'Colombia', 'CO'),
(37, 'Costa Rica', 'CR'),
(38, 'Cuba', 'CU'),
(39, 'Czech Republic (Česká Republika)', 'CZ'),
(40, 'Algérie', 'DZ'),
(41, 'Egypt', 'EG'),
(42, 'Finland', 'FI'),
(43, 'Ghana', 'GH'),
(44, 'Croatia (Hrvatska)', 'HR'),
(45, 'Christmas Island', 'CX'),
(46, 'Cyprus (Κύπρος)', 'CY'),
(47, 'Dominican Republic (República Dominicana)', 'DO'),
(48, 'Micronesia', 'FM'),
(49, 'Faroe Islands', 'FO'),
(50, 'French Guiana (Guyane Française)', 'GF'),
(51, 'Greenland', 'GL'),
(52, 'Guadeloupe', 'GP'),
(53, 'Estonia (Eesti)', 'EE'),
(54, 'Ecuador', 'EC'),
(55, 'Cabo Verde', 'CV'),
(56, 'Falkland Islands', 'FK'),
(57, 'Guernsey', 'GG'),
(58, 'Gibraltar', 'GI'),
(59, 'South Georgia & Sandwich', 'GS'),
(60, 'Guam', 'GU'),
(61, 'Heard & McDonald Islands', 'HM'),
(62, 'Haiti', 'HT'),
(63, 'Hungary (Magyarország)', 'HU'),
(64, 'Indonesia', 'ID'),
(65, 'British Indian Ocean Territory', 'IO'),
(66, 'Iraq', 'IQ'),
(67, 'Iran (ایران)', 'IR'),
(68, 'Jersey', 'JE'),
(69, 'Jamaica', 'JM'),
(70, 'Kenya', 'KE'),
(71, 'Kyrgyzstan (Киргизия)', 'KG'),
(72, 'Cambodia (កម្ពុជា)', 'KH'),
(73, 'South Korea (대한민국)', 'KR'),
(74, 'Kuwait (الكويت)', 'KW'),
(75, 'Cayman Islands', 'KY'),
(76, 'Kazakhstan (Қазақстан)', 'KZ'),
(77, 'Laos', 'LA'),
(78, 'Saint Lucia', 'LC'),
(79, 'Liechtenstein', 'LI'),
(80, 'Lesotho', 'LS'),
(81, 'Lietuva', 'LT'),
(82, 'Latvija', 'LV'),
(83, 'Morocco (المغرب)', 'MA'),
(84, 'Monaco', 'MC'),
(85, 'Moldova', 'MD'),
(86, 'Saint-Martin', 'MF'),
(87, 'Madagascar', 'MG'),
(88, 'North Macedonia', 'MK'),
(89, 'Mali', 'ML'),
(90, 'Mongolia (Монгол Улс)', 'MN'),
(91, 'Martinique', 'MQ'),
(92, 'Mauritius', 'MU'),
(93, 'Maldives', 'MV'),
(94, 'Malaysia', 'MY'),
(95, 'Mozambique (Moçambique)', 'MZ'),
(96, 'New Caledonia (Nouvelle-Calédonie)', 'NC'),
(97, 'Nigeria', 'NG'),
(98, 'Nicaragua', 'NI'),
(99, 'Nepal', 'NP'),
(100, 'Niue', 'NU'),
(101, 'New Zealand', 'NZ'),
(102, 'Peru (Perú)', 'PE'),
(103, 'French Polynesia (Polynésie française)', 'PF'),
(104, 'Philippines', 'PF'),
(105, 'Pakistan', 'PK'),
(106, 'Poland (Polska)', 'PL'),
(107, 'Saint Pierre and Miquelon (Saint-Pierre et Miquelon)', 'PM'),
(108, 'Pitcairn Islands', 'PN'),
(109, 'Puerto Rico', 'PR'),
(110, 'Palau', 'PW'),
(111, 'Paraguay', 'PY'),
(112, 'Réunion', 'RE'),
(113, 'Romania (România)', 'RO'),
(114, 'Serbia (Србија)', 'RS'),
(115, 'Saudi Arabia (السعودية)', 'SA'),
(116, 'Saint Helena', 'SH'),
(117, 'Slovenia', 'SL'),
(118, 'Svalbard and Jan Mayen (Svalbard og Jan Mayen)', 'SJ'),
(119, 'Slovakia (Slovensko)', 'SK'),
(120, 'San Marino', 'SM'),
(121, 'El Salvador', 'SV'),
(122, 'Swaziland', 'SZ'),
(123, 'Turks and Caicos Islands', 'TC'),
(124, 'Thailand (ประเทศไทย)', 'TH'),
(125, 'Turkmenistan', 'TM'),
(126, 'Tunisia (Tunisie)', 'TN'),
(127, 'Tanzania', 'TZ'),
(128, 'Minor Outlying Islands', 'UM'),
(129, 'Uruguay', 'UY'),
(130, 'Uruguay (Ўзбекистон)', 'UZ'),
(131, 'Sancta Sedes', 'VA'),
(132, 'Venezuela', 'VE'),
(133, 'British Virgin Islands', 'VG'),
(134, 'US Virgin Islands', 'VI'),
(135, 'Wallis and Futuna (Wallis-et-Futuna)', 'WF'),
(136, 'Mayotte', 'YT'),
(137, 'South Africa (Suid-Afrika)', 'ZA'),
(138, 'Norfolk Island', 'NF'),
(139, 'Turkey (Türkiye)', 'TR'),
(140, 'Taiwan (台湾小学)', 'TW'),
(141, 'Vietnam (Việt Nam)', 'VN'),
(142, 'Russia (Росси́я)', 'RU'),
(143, 'Ukraine (Україна)', 'UA'),
(144, 'Japan (日本)', 'JP'),
(145, 'China (中华人民共和国)', 'CN'),
(146, 'India', 'IN');